ServerEvents.tags('item', event => {
  event.add('cookingforblockheads:utensils', 'croptopia:cooking_pot')
  event.add('cookingforblockheads:utensils', 'croptopia:food_press')
  event.add('cookingforblockheads:utensils', 'croptopia:frying_pan')
  event.add('cookingforblockheads:utensils', 'croptopia:knife')
  event.add('cookingforblockheads:utensils', 'croptopia:mortar_and_pestle')

  event.add('cookingforblockheads:milk', 'croptopia:milk_bottle')
  event.add('cookingforblockheads:water', 'croptopia:water_bottle')

  event.add('cookingforblockheads:ingredients', 'croptopia:flour')
  event.add('cookingforblockheads:ingredients', 'croptopia:dough')
  event.add('cookingforblockheads:ingredients', 'croptopia:molasses')
  event.add('cookingforblockheads:ingredients', 'croptopia:soy_milk')
  event.add('cookingforblockheads:ingredients', 'croptopia:butter')
  event.add('cookingforblockheads:ingredients', 'croptopia:cheese')
  event.add('cookingforblockheads:ingredients', 'croptopia:salt')
  event.add('cookingforblockheads:ingredients', 'croptopia:bacon')
  event.add('cookingforblockheads:ingredients', 'croptopia:ground_pork')
  event.add('cookingforblockheads:ingredients', 'croptopia:sausage')
  event.add('cookingforblockheads:ingredients', 'croptopia:pepper')
  event.add('cookingforblockheads:ingredients', 'croptopia:paprika')
  event.add('cookingforblockheads:ingredients', 'croptopia:noodle')
  event.add('cookingforblockheads:ingredients', 'croptopia:tortilla')
  event.add('cookingforblockheads:ingredients', 'croptopia:olive_oil')
  event.add('cookingforblockheads:ingredients', 'croptopia:cooking_oil')
  event.add('cookingforblockheads:ingredients', 'croptopia:yeast')
  event.add('cookingforblockheads:ingredients', 'croptopia:tofu')
  event.add('cookingforblockheads:ingredients', 'croptopia:grilled_sausage')
  event.add('cookingforblockheads:ingredients', 'croptopia:soy_sauce')
  event.add('cookingforblockheads:ingredients', 'croptopia:vinegar')
  event.add('cookingforblockheads:ingredients', 'croptopia:sugar')
  event.add('cookingforblockheads:ingredients', 'croptopia:caramel')
  event.add('cookingforblockheads:ingredients', 'croptopia:nutmeg')
  event.add('cookingforblockheads:ingredients', 'croptopia:cinnamon')
  event.add('cookingforblockheads:ingredients', 'croptopia:vanilla')
  event.add('cookingforblockheads:ingredients', 'croptopia:baking_soda')
  event.add('cookingforblockheads:ingredients', 'croptopia:baking_powder')
  event.add('cookingforblockheads:ingredients', 'croptopia:coconut')
  event.add('cookingforblockheads:ingredients', 'croptopia:raisins')
  event.add('cookingforblockheads:ingredients', 'croptopia:corn_husk')
  event.add('cookingforblockheads:ingredients', 'croptopia:cucumber')
  event.add('cookingforblockheads:ingredients', 'croptopia:pickles')
  event.add('cookingforblockheads:ingredients', 'croptopia:kale')
  event.add('cookingforblockheads:ingredients', 'croptopia:soybean')
  event.add('cookingforblockheads:ingredients', 'croptopia:leek')
  event.add('cookingforblockheads:ingredients', 'croptopia:scallion')
  event.add('cookingforblockheads:ingredients', 'croptopia:asparagus')
  event.add('cookingforblockheads:ingredients', 'croptopia:rhubarb')
  event.add('cookingforblockheads:ingredients', 'croptopia:radish')
  event.add('cookingforblockheads:ingredients', 'croptopia:zucchini')
  event.add('cookingforblockheads:ingredients', 'croptopia:artichoke')
  event.add('cookingforblockheads:ingredients', 'croptopia:turnip')
  event.add('cookingforblockheads:ingredients', 'croptopia:celery')
  event.add('cookingforblockheads:ingredients', 'croptopia:broccoli')
  event.add('cookingforblockheads:ingredients', 'croptopia:cauliflower')
  event.add('cookingforblockheads:ingredients', 'croptopia:eggplant')
  event.add('cookingforblockheads:ingredients', 'croptopia:olive')
  event.add('cookingforblockheads:ingredients', 'croptopia:onion')
})

ServerEvents.recipes(event => {
  event.remove({ id: 'croptopia:sausage' })
  event.shapeless(
    Item.of('croptopia:sausage', 1),
    ['croptopia:ground_pork', 'croptopia:salt', 'croptopia:paprika']
  )
})
