ServerEvents.tags('item', event => {
  event.add('cookingforblockheads:utensils', 'croptopia:cooking_pot')
  event.add('cookingforblockheads:utensils', 'croptopia:food_press')
  event.add('cookingforblockheads:utensils', 'croptopia:frying_pan')
  event.add('cookingforblockheads:utensils', 'croptopia:knife')
  event.add('cookingforblockheads:utensils', 'croptopia:mortar_and_pestle')

  event.add('cookingforblockheads:milk', 'croptopia:milk_bottle')
  event.add('cookingforblockheads:water', 'croptopia:water_bottle')

  event.add('cookingforblockheads:ingredients', 'croptopia:flour')
  event.add('cookingforblockheads:ingredients', 'croptopia:dough')
  event.add('cookingforblockheads:ingredients', 'croptopia:molasses')
  event.add('cookingforblockheads:ingredients', 'croptopia:soy_milk')
  event.add('cookingforblockheads:ingredients', 'croptopia:butter')
  event.add('cookingforblockheads:ingredients', 'croptopia:cheese')
  event.add('cookingforblockheads:ingredients', 'croptopia:salt')
  event.add('cookingforblockheads:ingredients', 'croptopia:bacon')
  event.add('cookingforblockheads:ingredients', 'croptopia:ground_pork')
  event.add('cookingforblockheads:ingredients', 'croptopia:sausage')
  event.add('cookingforblockheads:ingredients', 'croptopia:pepper')
  event.add('cookingforblockheads:ingredients', 'croptopia:paprika')
  event.add('cookingforblockheads:ingredients', 'croptopia:noodle')
  event.add('cookingforblockheads:ingredients', 'croptopia:tortilla')
  event.add('cookingforblockheads:ingredients', 'croptopia:olive_oil')
  event.add('cookingforblockheads:ingredients', 'croptopia:cooking_oil')
  event.add('cookingforblockheads:ingredients', 'croptopia:yeast')
  event.add('cookingforblockheads:ingredients', 'croptopia:tofu')
})
