name = "Summer 2026 Survival"
author = "minecraftsummer2026"
version = "1.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd9082a92352464d935a2147594a9cc172d56dbcf4afde00832347a2a61b0b14"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.76"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
