name = "Summer 2026 Survival"
author = "minecraftsummer2026"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "723e0aa0d8fc89003114c6e16f95b18c939b6c51d4b5b76c4b68220eeb62234f"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.76"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
