name = "Summer 2026 Survival Server"
author = "minecraftsummer2026"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f4759f75501273317e4b9e3f5e0d74da1595577b73e34a63361693c6bc31988"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.76"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
