name = "Summer 2026 Survival Server"
author = "minecraftsummer2026"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5a3a215b113bc788a2bb4a90078399b2e2751f2a80a4b9184b725dc92cc92cb"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.76"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
