# Summer 2026 Survival — Server Properties
# Minecraft 26.1.2 — NeoForge 26.1.2.74

allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
difficulty=normal
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enforce-whitelist=false
force-gamemode=false
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
level-name=world
level-seed=
level-type=default
max-chained-neighbor-updates=1000
max-players=8
max-tick-time=60000
max-world-size=29999984
motd=Summer 2026 Survival
network-compression-threshold=256
online-mode=true
op-permission-level=3
player-idle-timeout=30
prevent-proxy-connections=false
pvp=true
rate-limit=0
server-ip=
server-port=25565
simulation-distance=12
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=12
white-list=false